version: 2
jobs:
  build:
    docker:
      - image: ishiko/gcc-ishiko-cpp-build-prerequisites:0.3.0
    steps:
      - run: 
          name: "Set ISHIKO_CPP environment variable and create workspace directory"
          command: mkdir -p /projects/ishiko/cpp && echo 'export ISHIKO_CPP="/projects/ishiko/cpp"' >> $BASH_ENV
      - checkout:
          path: /projects/ishiko/cpp/concurrency
      - run:
          name: Build
          command: cd /projects/ishiko/cpp/concurrency/build/gnumake && make
      - run:
          name: Test build
          command: cd /projects/ishiko/cpp/concurrency/tests/build/gnumake && make
      - run:
          name: Run the tests
          command: cd /projects/ishiko/cpp/concurrency/tests/build/gnumake && ./IshikoConcurrencyTests
workflows:
  version: 2
  continuous_build:
    jobs:
      - build
  weekly_build:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
